---
title: "HT-4"
author: "Diego-Fabian"
date: "`r Sys.Date()`"
output: html_document
---

#División del conjunto de datos en entrenamiento y prueba

```{r setup}
# Carga de librerías necesarias
library(rpart)
library(rpart.plot)
library(caret)

# Cargar el conjunto de datos
data <- read.csv("train.csv")  # Asegúrate de que 'train.csv' es el archivo correcto

# Asumiendo que ya tienes definidos train_data y test_data desde la hoja de trabajo anterior
# Si necesitas dividir los datos, puedes usar la función createDataPartition() de caret
 set.seed(123)  # Establecer una semilla para reproducibilidad
 index <- createDataPartition(data$SalePrice, p = 0.8, list = FALSE)
 train_data <- data[index, ]
 test_data <- data[-index, ]
dim(train_data)
dim(test_data)

```

##Construccion del arbol de regresión
```{r arbol}
# Eliminar 'Condition2' de los conjuntos de entrenamiento y prueba
train_data$Condition2 <- NULL
test_data$Condition2 <- NULL
# Construir el árbol de regresión usando todas las variables
tree_model <- rpart(SalePrice ~ ., data = train_data, method = "anova")

# Visualizar el árbol
rpart.plot(tree_model, main="Árbol de Regresión")

```

## Prediccion y análisis de los resultados
```{r predict}

# Realizar predicciones en el conjunto de prueba
predictions <- predict(tree_model, test_data)

# Calcular y mostrar el Error Cuadrático Medio (MSE)
mse <- mean((predictions - test_data$SalePrice)^2)
print(paste("Error Cuadrático Medio (MSE):", mse))

```

